import { ToolDefinition } from "./schema-types";

export const PRESET_TEMPLATES: Record<string, ToolDefinition> = {
  web_search: {
    id: "preset_web_search",
    name: "web_search",
    description: "Search the public web and return curated snippets, titles, and ranking citations.",
    strict: true,
    parameters: [
      {
        id: "p1",
        name: "query",
        type: "string",
        description: "The targeted keywords or search query to execute.",
        required: true,
        minLength: 2,
      },
      {
        id: "p2",
        name: "max_results",
        type: "integer",
        description: "Maximum number of search results to return (between 1 and 20).",
        required: false,
        default: 5,
        minimum: 1,
        maximum: 20,
      },
      {
        id: "p3",
        name: "filter_type",
        type: "enum",
        description: "Result category filtering preference.",
        required: false,
        enumOptions: ["all", "news", "code", "academic", "discussions"],
        default: "all",
      },
      {
        id: "p4",
        name: "domains",
        type: "array",
        description: "List of specific domain names to restrict search results to.",
        required: false,
        itemType: "string",
      },
    ],
  },

  sql_database_query: {
    id: "preset_sql_db",
    name: "sql_database_query",
    description: "Execute a read-only SQL query against the connected relational database engine.",
    strict: true,
    parameters: [
      {
        id: "s1",
        name: "query",
        type: "string",
        description: "The sanitized SQL query statement to run.",
        required: true,
      },
      {
        id: "s2",
        name: "database_target",
        type: "enum",
        description: "Target database connection pool.",
        required: true,
        enumOptions: ["production_analytics", "staging_replica", "warehouse_clickhouse"],
        default: "production_analytics",
      },
      {
        id: "s3",
        name: "timeout_ms",
        type: "integer",
        description: "Query execution timeout threshold in milliseconds.",
        required: false,
        default: 5000,
        minimum: 500,
        maximum: 30000,
      },
      {
        id: "s4",
        name: "explain_plan",
        type: "boolean",
        description: "If true, returns the EXPLAIN execution plan instead of executing the query.",
        required: false,
        default: false,
      },
    ],
  },

  github_issue_creator: {
    id: "preset_github_issue",
    name: "create_github_issue",
    description: "Open a new issue or feature request in the specified GitHub repository.",
    strict: true,
    parameters: [
      {
        id: "g1",
        name: "repository",
        type: "string",
        description: "Full owner/repo identifier (e.g. 'octocat/Hello-World').",
        required: true,
      },
      {
        id: "g2",
        name: "title",
        type: "string",
        description: "Brief summary of the issue or feature request.",
        required: true,
        maxLength: 120,
      },
      {
        id: "g3",
        name: "body",
        type: "string",
        description: "Comprehensive issue description including repro steps and environment context.",
        required: true,
      },
      {
        id: "g4",
        name: "labels",
        type: "array",
        description: "GitHub tag labels to assign immediately.",
        required: false,
        itemType: "string",
      },
      {
        id: "g5",
        name: "priority",
        type: "enum",
        description: "Triage priority tier.",
        required: false,
        enumOptions: ["low", "medium", "high", "critical"],
        default: "medium",
      },
    ],
  },

  invoice_generator: {
    id: "preset_invoice",
    name: "generate_customer_invoice",
    description: "Generates an itemized customer billing invoice with tax calculations.",
    strict: true,
    parameters: [
      {
        id: "i1",
        name: "customer_id",
        type: "string",
        description: "Unique identifier for the billing account customer.",
        required: true,
      },
      {
        id: "i2",
        name: "currency",
        type: "enum",
        description: "Three-letter ISO currency code.",
        required: true,
        enumOptions: ["USD", "EUR", "GBP", "CAD", "AUD", "JPY"],
        default: "USD",
      },
      {
        id: "i3",
        name: "items",
        type: "array",
        description: "List of itemized invoice line entries.",
        required: true,
        itemType: "object",
        itemProperties: [
          {
            id: "i3_1",
            name: "sku",
            type: "string",
            description: "Product Stock Keeping Unit identifier.",
            required: true,
          },
          {
            id: "i3_2",
            name: "quantity",
            type: "integer",
            description: "Number of units purchased.",
            required: true,
            minimum: 1,
            default: 1,
          },
          {
            id: "i3_3",
            name: "unit_price",
            type: "number",
            description: "Price per individual unit.",
            required: true,
            minimum: 0,
          },
          {
            id: "i3_4",
            name: "tax_exempt",
            type: "boolean",
            description: "Whether sales tax is waived for this line item.",
            required: false,
            default: false,
          },
        ],
      },
      {
        id: "i4",
        name: "notes",
        type: "string",
        description: "Custom memo or terms shown on invoice footer.",
        required: false,
      },
    ],
  },
};
